language: scala
jdk:
  - oraclejdk7
  - openjdk6

script: 
  - sbt plugin/compile plugin/publishLocal
  - sbt ++2.10.4 core/compile core/publishLocal
  - sbt ++2.11.4 core/compile core/publishLocal scripted

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/69ff862d9939395b4d5d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


